//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcReserHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public habitacion()
        {
            this.habitacion_reservada = new HashSet<habitacion_reservada>();
        }
    
        public int cod_habitacion { get; set; }
        public Nullable<int> cod_estado { get; set; }
        public Nullable<int> cod_tipo_habitacion { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual tipo_habitacion tipo_habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<habitacion_reservada> habitacion_reservada { get; set; }
    }
}
