//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcReserHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitacion
    {
        public int cod_habitacion { get; set; }
        public Nullable<int> cod_estado { get; set; }
        public Nullable<int> cod_tipo_habitacion { get; set; }
        public Nullable<int> cod_reservacion { get; set; }
    
        public virtual estado estado { get; set; }
        public virtual reservacion reservacion { get; set; }
        public virtual tipo_habitacion tipo_habitacion { get; set; }
    }
}
